model:
  type: 'PointNetPartSegMean'

dataset:
  type: 'ShapeNet'
  categories: 'All'
  repeat_to: 4096

train:
  type: 'train_part_seg'

test:
  type: 'test_part_seg'

dataloader:
  type: 'DataListLoader'
  batch_size: 96
  num_workers: 16
